import React from 'react';
import { createRoot } from 'react-dom/client';
import 'beds/styles.css';
import Catalog from './Catalog';
import LucyPage from './LucyPage';
import McpPage from './McpPage';
import DisclosuresPage from './DisclosuresPage';
import LandingExamples from './LandingExamples';
const params = new URLSearchParams(location.search);
const isLucy = params.get('view') === 'lucy' || (params.get('view') === 'home' && params.get('tab') === 'lucy');
const isMcp = params.get('view') === 'mcp';
const isDisclosures = params.get('view') === 'disclosures';
const isLanding = params.get('view') === 'landing';
createRoot(document.getElementById('root')!).render(<React.StrictMode>{isDisclosures ? <DisclosuresPage /> : isMcp ? <McpPage /> : isLucy ? <LucyPage /> : isLanding ? <LandingExamples /> : <Catalog />}</React.StrictMode>);
